"""Add account_id to draft_history for per-account isolation.

Before this migration, draft_history had no account_id column, which
caused a cross-account leak: GET /api/drafts returned every draft ever
generated by any account, because both SqliteDraftHistoryAdapter and
LegacyDraftHistoryAdapter emitted `SELECT * FROM draft_history` with
no WHERE clause.

Strategy:
  1. Add a nullable account_id column with FK + CASCADE to accounts(id).
  2. Backfill by resolving each row's email_sender → owning account via
     the `accounts` table (best-effort — rows with no match stay NULL
     and are then hard-quarantined so they never surface in any user's
     list).
  3. Add composite index (account_id, created_at) for fast list queries.

The adapter and routes code enforces that NULL account_id rows are
never returned, which is the safety net that makes the backfill
misclassification impossible to leak.

Revision ID: 014_add_account_id_to_draft_history
Revises: 013_add_contact_summary
Create Date: 2026-04-15 00:00:01
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "014_add_account_id_to_draft_history"
down_revision: Union[str, None] = "013_add_contact_summary"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    return table_name in set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    if not _table_exists("draft_history"):
        return

    # 1. Add the column (nullable — FK enforced, CASCADE on account delete).
    with op.batch_alter_table("draft_history") as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_draft_history_account_id_accounts",
            "accounts",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # 2. Backfill from accounts.email when the draft's email_sender is
    #    actually the owning account (rare for received-email drafts, but
    #    covers self-sent / reply-to-self / compose drafts).
    op.execute(
        """
        UPDATE draft_history
        SET account_id = (
            SELECT a.id FROM accounts a
            WHERE LOWER(a.email) = LOWER(draft_history.email_sender)
            LIMIT 1
        )
        WHERE account_id IS NULL
          AND email_sender IS NOT NULL
          AND email_sender != ''
        """
    )

    # 3. Composite index for the hot query path.
    op.create_index(
        "idx_draft_history_account_created",
        "draft_history",
        ["account_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("idx_draft_history_account_created", table_name="draft_history")
    with op.batch_alter_table("draft_history") as batch_op:
        batch_op.drop_constraint(
            "fk_draft_history_account_id_accounts", type_="foreignkey"
        )
        batch_op.drop_column("account_id")
