/**
 * useGmailAuth - React hook for Gmail OAuth authentication
 *
 * This is a wrapper around the unified useOAuth hook for backwards compatibility.
 * New code should use useOAuth or useGmailOAuth directly.
 *
 * Migration notes:
 * - Tokens are now stored server-side, not in OS Keychain
 * - getAccessToken() is deprecated - backend handles token access
 * - refreshToken() now calls the server-side refresh endpoint
 */

import { useCallback, useEffect, useState } from 'react'
import { useOAuth, type ConnectOptions } from './useOAuth'
import { API_URL } from '../config'

export type AuthStatus = 'disconnected' | 'connecting' | 'connected' | 'error'

export interface GmailAuthState {
  status: AuthStatus
  email: string | null
  error: string | null
  isLoading: boolean
  popupBlocked: boolean
  pollingStalled: boolean
}

export interface UseGmailAuthResult extends GmailAuthState {
  connect: (options?: ConnectOptions) => Promise<void>
  cancelConnect: () => void
  disconnect: () => Promise<void>
  refreshToken: () => Promise<void>
  /**
   * @deprecated Access tokens are now managed server-side.
   * Use the backend API endpoints which automatically include auth.
   */
  getAccessToken: () => Promise<string | null>
}

export function useGmailAuth(accountId: string): UseGmailAuthResult {
  const oauth = useOAuth('gmail', accountId)
  const [effectiveAccountId, setEffectiveAccountId] = useState<string>(accountId)

  // Track the account ID from OAuth (might be generated by server)
  useEffect(() => {
    if (oauth.accountId) {
      setEffectiveAccountId(oauth.accountId)
    }
  }, [oauth.accountId])

  // Refresh tokens via server
  const refreshToken = useCallback(async () => {
    try {
      const response = await fetch(
        `${API_URL}/api/oauth/tokens/${effectiveAccountId}/refresh`,
        { method: 'POST' }
      )
      if (!response.ok) {
        throw new Error('Token refresh failed')
      }
      // Re-check status after refresh
      await oauth.checkStatus()
    } catch (error) {
      console.error('[useGmailAuth] refreshToken failed:', error)
    }
  }, [effectiveAccountId, oauth])

  // Deprecated: Get access token
  // Tokens are now managed server-side
  const getAccessToken = useCallback(async (): Promise<string | null> => {
    console.warn(
      '[useGmailAuth] getAccessToken is deprecated. ' +
        'Access tokens are now managed server-side.'
    )

    try {
      const response = await fetch(
        `${API_URL}/api/oauth/tokens/${effectiveAccountId}/access`
      )
      if (!response.ok) {
        return null
      }
      const data = await response.json()
      return data.access_token
    } catch {
      return null
    }
  }, [effectiveAccountId])

  return {
    status: oauth.status,
    email: oauth.email,
    error: oauth.error,
    isLoading: oauth.isLoading,
    popupBlocked: oauth.popupBlocked,
    pollingStalled: oauth.pollingStalled,
    connect: oauth.connect,
    cancelConnect: oauth.cancelConnect,
    disconnect: oauth.disconnect,
    refreshToken,
    getAccessToken,
  }
}
